= Antora Indexer CLI Tool

This tool generates two sets of JSON files that are required for the Lunr.js https://github.com/vshn/embedded-search-engine/[embedded search engine] to work.

This application is written with http://www.typescriptlang.org/[TypeScript] and is built with https://gulpjs.com/[Gulp].

== Requirements

After cloning this repo, call the `npm install` command to install all dependencies.

Then run the `gulp` command to build the `dist/indexer.js`.

The application can be run using Node:

`node dist/indexer.js --help`

== Docker

=== Building the Image

Run the `docker build -t vshn/antora-indexer-cli .` command to build the image.

== Docker Image Usage

Once pushed, the following command will output the Lunr.js index for the Antora documentation located in the `~/project/docs` folder:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --path /docs --output index`

The list of files (used to generate user-friendly search results) can be generated with the `--output files` option:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --path /docs --output files`

Users can learn more about this application using the command:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --help`
