= Antora Indexer CLI Tool

This tool generates two JSON files required for the Lunr.js-based https://github.com/vshn/embedded-search-engine/[embedded search engine] to work.

This application is written with http://www.typescriptlang.org/[TypeScript] and is built with https://gulpjs.com/[Gulp].

== Requirements

After cloning this repo, call the `npm install` command to install all dependencies.

Then run the `gulp` command to build the `dist/antora-indexer.js`.

The application can be run using Node:

`dist/antora-indexer.js --help`

== Command Line Options

[source]
----
Usage: antora-indexer [options]

Options:
  -V, --version        output the version number
  -a, --antora <path>  (mandatory) path of the Antora project to parse
  -w, --write <kind>   valid values: "index" or "files" (default: "index")
  -o, --output <path>  (optional) write to the specified path instead of stdout
  -h, --help           output usage information
----

== Tests

The test suite is based on https://jasmine.github.io/[Jasmine]. Run all the tests with this command:

`npm test`

== Docker

=== Building the Image

Run the `docker build -t vshn/antora-indexer-cli .` command to build the image.

== Docker Image Usage

Once pushed, the following command will output the Lunr.js index for the Antora documentation located in the `~/project/docs` folder:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --antora /docs --write index`

The list of files (used to generate user-friendly search results) can be generated with the `--write files` option:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --antora /docs --write files`

Users can learn more about this application using the command:

`docker run --rm --interactive --tty --volume ~/project/docs:/docs vshn/antora-indexer-cli --help`
