= How to Use

To use the application, invoke it at the command line with the following options:

[source]
----
Usage: antora-indexer [options]

Options:
  -V, --version          output the version number
  -p, --playbook <path>  (mandatory) path of the Antora project to parse
  -a, --antora <path>    (mandatory) path of the Antora project to parse
  -w, --write <kind>     valid values: "index" or "files" (default: "index")
  -o, --output <path>    (optional) write to the specified path instead of stdout
  -h, --help             output usage information
----

== Flags

The tool requires either the `--playbook` or the `--antora` flag to work; the former specifies the absolute path to a `playbook.yml` file, while the latter specifies the path to an `antora.yml` file.

The `--write` flag has two options:

* `index` which specifies the creation of the `index.json` file, containing the actual https://lunrjs.com/[Lunr.js] index used for searches.
* `files` which specifies the creation of the `files.json` file, containing metadata about each search result found in the index.

IMPORTANT: Why does this tool generate two files? Because the `index.json` file generated by https://lunrjs.com/[Lunr.js] does not contain useful metadata for the user, like the title of the file (read from the Asciidoc source) or a short snippet showing its contents. The Embedded Search Engine uses that information provide nice search results to the user.

The tool writes its output to `stdout` by default. Use the `--output` flag to specify an output path. Any files in that path will be overwritten.

== Parsing `playbook.yml` Files

When the user specifies the `--playbook` flag, the tool will use the https://isomorphic-git.org/[Isomorphic Git] library to clone all referenced projects, and proceed to index each and every one of them.

NOTE: When using the `--antora` flag, the tool performs no Git operation whatsoever, simply reading the files from disk.
